import type { Metadata } from "next";
import { Noto_Sans_JP, Figtree } from 'next/font/google'
import "./globals.scss";
import "../styles/home.scss";
import "../styles/works.scss";
import Header from '../components/Header';

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
})

const figtree = Figtree({
  subsets: ['latin'],
  variable: '--font-figtree',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${notoSansJP.variable} ${figtree.variable}`}>
      <body className="has-[.micromodal-slide.is-open]:overflow-hidden">
        <div className="overflow-hidden">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
